spring:
  application:
    name: gateway-api
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_URL:http://localhost:8082/}realms/digitalMedia
            token-uri: ${KEYCLOAK_URL:http://localhost:8082/}realms/digitalMedia/protocol/openid-connect/token
            authorization-uri: http://localhost:8082/realms/digitalMedia/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8082/realms/digitalMedia/protocol/openid-connect/userinfo
            scope: openid
        registration:
          gateway-api:
            provider: keycloak
            client-id: api-gateway
            client-secret: gBta9DE3d7NeQ1e6dyZpQJzm9lHLqTKv
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8082/login/oauth2/code/keycloak
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      default-filters:
        - TokenRelay
      routes:
        - id: moviesRoute
          uri: lb://movies-service
          predicates:
            - Path=/movies/**
        - id: billsRoute
          uri: lb://bills-service
          predicates:
            - Path=/bills/**
        - id: usersRoute
          uri: lb://users-service
          predicates:
            - Path=/users/**


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    enabled: true