server:
  port: 8888
spring:
  application:
    name: configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MejiaOrtizAG/configuration_files/
          searchPaths: configuration_digitalmedia
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Config Microservice